### ISSUE TITLE
Reduce Kintex7 boot time when loading from flash

### ISSUE THREAD

**Issue by unbtorsten** [trabucayre/openFPGALoader#181]
_Original discussion in https://github.com/trabucayre/openFPGALoader/issues/180#issuecomment-1048030988_ and following.

Expedite booting from flash by
- add bitstream compression
  ```
  set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
  ```
- configure quad mode
  ```
  set_property CONFIG_MODE SPIx4 [current_design]
  ```

**Comment by jrrk2** [comment]
I can see a benefit in download time of the spiOverJtag bit image to ram due to this technique. However I don't think quad mode in the Vivado project will do anything for speed of the eventual BitStream load from flash. We can do diffs between .MCS files from Vivado with and without the quad mode to see what the difference is and whether you can exploit that in your bitstream to flash converter,

**Comment by unbtorsten** [comment]
@jrrk2, @trabucayre: Including configuration above does not make a difference for boot time. This agrees with jrrk2's comment above.

**Comment by trabucayre** [comment]
> @jrrk2, @trabucayre: Including configuration above does not make a difference for boot time. This agrees with jrrk2's comment above.

Quad mode + compression has no impact to boot time? It's a strange thing. Make sense to dump bitstream for comparison.

**Comment by jrrk2** [comment]
But for the bitstream written in flash it is also useless at the moment because the open source toolchain does not know to treat this option.

**Comment by jrrk2** [comment]
However I would expect the spiOverJtag bitstream to load quicker. But the compression ratio will be strongly dependent on the number of PIPs that are turned on, which is next to nothing with this design.

**Comment by jrrk2** [comment]
write_cfgmem  -format bin -size 32 -interface SPIx4 -loadbit "up 0x00000000 $bitfile" -file "$binfile"

As per this command, we can see the quad mode is introduced during conversion from bitstream to binfile/mcsfile. So this is where we need to look to gain performance, rather than in the spiOverJtag Vivado settings

**Comment by trabucayre** [comment]
Feel free to reopen this one if something may be done at openFPGALoader level
