### ISSUE TITLE
how to build static executable

### ISSUE THREAD

**Issue by emard** [trabucayre/openFPGALoader#23]
Feature wish: a short note in readme on how to build
static executable, independent from shared libraries.

It could increases portability of compiled executable
accross various linux distro's.

**Comment by trabucayre** [comment]
Good idea.
Currently, this feature is not supported. I've just tried after some modifications in CMakeLists.txt but in my distro udev as no .a and the build fails. I need to find a distribution where all required .a are present to validate modifications before pushing.

**Comment by kost** [comment]
Here's the changes I have done together with process which builds openFPGAloader without problems:

https://github.com/alpin3/ulx3s-core/commit/810193f0615069328f219c9d5766471dd13cd4c2

I'm using Docker on Alpine with Eudev library:
https://wiki.gentoo.org/wiki/Eudev

Also, have to use argp-standalone apk package since you're using argp.h which is glibc specific.

**Comment by trabucayre** [comment]
Thank for this link.
I've just push a test (and note) to use argp-standalone for musl or uClibc.
I'll just doing some verifications before applying your proposition for static libs but look good.

**Comment by trabucayre** [comment]
Based on kost's patch I've added STATIC_BUILD option and updated README.
If it's good for you, and if you're agree, I close this issue.

**Comment by emard** [comment]
I agree :)

**Comment by trabucayre** [comment]
Great
