### ISSUE TITLE
DATA_DIR override with environment variable

### ISSUE THREAD

**Issue by mmicko** [trabucayre/openFPGALoader#333]
Would it be possible to add ability to override DATA_DIR location with environment variable ( OPENFPGA_LOADER_DIR for example) ? With oss-cad-suite can place their files anywhere, so using environment variable or checking it relative to binary position are only options.

https://github.com/trabucayre/openFPGALoader/blob/master/src/xilinx.cpp#L472

**Comment by trabucayre** [comment]
Is [this solution](https://github.com/trabucayre/openFPGALoader/commit/cd8a143164340493ef5dea3984ce9b0412cf36d3) looks good to you?
With this commit if you set `OPENFPGALOADER_SOJ_DIR` to priovides an alternate *spiOverJtag* bitstreams directory, this directory will be used, instead of `DATA_DIR` to open the bridge.

**Comment by mmicko** [comment]
Thanks @trabucayre this looks just right. Will work on change required on oss-cad-suite tomorrow.

**Comment by mmicko** [comment]
Thanks, all working now as expected
