### ISSUE TITLE
Unable to program CertusPro NX dv

### ISSUE THREAD

**Issue by vishnutskumar** [trabucayre/openFPGALoader#430]
![image](https://github.com/trabucayre/openFPGALoader/assets/64924618/5fa83c25-c2f1-4f01-a10f-3497818e3491)

The error is thrown at line 71 in latticeBitParser.cpp
![image](https://github.com/trabucayre/openFPGALoader/assets/64924618/c59c6ece-d57d-4b41-8c51-23fe7e0f19d1)

The bitstream generated by Radiant(lattice tool) has 0xbe instead of 0xbd or 0xbf 
![image](https://github.com/trabucayre/openFPGALoader/assets/64924618/aa865636-8426-485e-a6da-3b22807359bf)

**Comment by trabucayre** [comment]
Have you enabled some options?
maybe @bg-gsl has more idea. In fact I haven't an FPGA to this family...
If nothing I have to study documentation to this something like that.

Thanks

**Comment by bg-gsl** [comment]
Hej! :)

May I ask whether the bitstream is encoded? i.e. whether you generated it with the setting "IP Evaluation" being active in Project -> Active Strategy -> Bitstream Setting in Radiant?

**Comment by vishnutskumar** [comment]
hey @bg-gsl , yes the bitstream is set with IP evaluation ON. If it isn't ON, I get the following error while trying to export the design
![image](https://github.com/trabucayre/openFPGALoader/assets/64924618/5f2e0c53-84b9-4923-9b8b-6f6eedfc8c55)

**Comment by bg-gsl** [comment]
Hej!
Thanks for the info.
This behaviour is the expected one. I have plans to look into add the capability of loading encrypted bitstreams to Lattice Nexus FPGAs, but I cannot guarantee when nor if it will work. Probably I should have documented it somehow: @trabucayre do you know how this could be done?

About your error: I guess it's because you don't have a license for Radiant for CertusPro-NX devices. While it is not needed if you're targeting Crosslink or Certus FPGAs, you have to buy a license for targeting CertusPro https://www.latticesemi.com/en/Support/Licensing

**Comment by bg-gsl** [comment]
Hej!

I've created a pull request that should enable downloading of encrypted bitstreams on Lattice Nexus FPGAs https://github.com/trabucayre/openFPGALoader/pull/432
Let me know if things work!

**Comment by vishnutskumar** [comment]
Hey,

Thanks for the update, it works really well now!
